<?php
/**
 * AngazmaOsobaVr
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARES: REST API - veřejné
 *
 * REST rozhraní systému ARES
 *
 * OpenAPI spec version: 0.6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ares\Client\Model;
use \Ares\Client\ObjectSerializer;

/**
 * AngazmaOsobaVr Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AngazmaOsobaVr extends DatumZapisuVymazuUdajeVr 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AngazmaOsobaVr';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'skryty_udaj' => '\Ares\Client\Model\ObecnyTextVr',
        'clenstvi' => '\Ares\Client\Model\AngazmaClenstviVr',
        'pravnicka_osoba' => '\Ares\Client\Model\PravnickaOsobaVr',
        'fyzicka_osoba' => '\Ares\Client\Model\FyzickaOsobaVr'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'skryty_udaj' => null,
        'clenstvi' => null,
        'pravnicka_osoba' => null,
        'fyzicka_osoba' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'skryty_udaj' => 'skrytyUdaj',
        'clenstvi' => 'clenstvi',
        'pravnicka_osoba' => 'pravnickaOsoba',
        'fyzicka_osoba' => 'fyzickaOsoba'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'skryty_udaj' => 'setSkrytyUdaj',
        'clenstvi' => 'setClenstvi',
        'pravnicka_osoba' => 'setPravnickaOsoba',
        'fyzicka_osoba' => 'setFyzickaOsoba'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'skryty_udaj' => 'getSkrytyUdaj',
        'clenstvi' => 'getClenstvi',
        'pravnicka_osoba' => 'getPravnickaOsoba',
        'fyzicka_osoba' => 'getFyzickaOsoba'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }




    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['skryty_udaj'] = isset($data['skryty_udaj']) ? $data['skryty_udaj'] : null;
        $this->container['clenstvi'] = isset($data['clenstvi']) ? $data['clenstvi'] : null;
        $this->container['pravnicka_osoba'] = isset($data['pravnicka_osoba']) ? $data['pravnicka_osoba'] : null;
        $this->container['fyzicka_osoba'] = isset($data['fyzicka_osoba']) ? $data['fyzicka_osoba'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets skryty_udaj
     *
     * @return \Ares\Client\Model\ObecnyTextVr
     */
    public function getSkrytyUdaj()
    {
        return $this->container['skryty_udaj'];
    }

    /**
     * Sets skryty_udaj
     *
     * @param \Ares\Client\Model\ObecnyTextVr $skryty_udaj skryty_udaj
     *
     * @return $this
     */
    public function setSkrytyUdaj($skryty_udaj)
    {
        $this->container['skryty_udaj'] = $skryty_udaj;

        return $this;
    }

    /**
     * Gets clenstvi
     *
     * @return \Ares\Client\Model\AngazmaClenstviVr
     */
    public function getClenstvi()
    {
        return $this->container['clenstvi'];
    }

    /**
     * Sets clenstvi
     *
     * @param \Ares\Client\Model\AngazmaClenstviVr $clenstvi clenstvi
     *
     * @return $this
     */
    public function setClenstvi($clenstvi)
    {
        $this->container['clenstvi'] = $clenstvi;

        return $this;
    }

    /**
     * Gets pravnicka_osoba
     *
     * @return \Ares\Client\Model\PravnickaOsobaVr
     */
    public function getPravnickaOsoba()
    {
        return $this->container['pravnicka_osoba'];
    }

    /**
     * Sets pravnicka_osoba
     *
     * @param \Ares\Client\Model\PravnickaOsobaVr $pravnicka_osoba pravnicka_osoba
     *
     * @return $this
     */
    public function setPravnickaOsoba($pravnicka_osoba)
    {
        $this->container['pravnicka_osoba'] = $pravnicka_osoba;

        return $this;
    }

    /**
     * Gets fyzicka_osoba
     *
     * @return \Ares\Client\Model\FyzickaOsobaVr
     */
    public function getFyzickaOsoba()
    {
        return $this->container['fyzicka_osoba'];
    }

    /**
     * Sets fyzicka_osoba
     *
     * @param \Ares\Client\Model\FyzickaOsobaVr $fyzicka_osoba fyzicka_osoba
     *
     * @return $this
     */
    public function setFyzickaOsoba($fyzicka_osoba)
    {
        $this->container['fyzicka_osoba'] = $fyzicka_osoba;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
