<?php
/**
 * EZP
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARES: REST API - veřejné
 *
 * REST rozhraní systému ARES
 *
 * OpenAPI spec version: 0.6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ares\Client\Model;

use \ArrayAccess;
use \Ares\Client\ObjectSerializer;

/**
 * EZP Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EZP implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EZP';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'evidence_od' => '\DateTime',
        'angazovany_subjekt' => '\Ares\Client\Model\AngazovanySubjektSzr',
        'v_evidenci' => 'bool',
        'urad_evidence' => 'string',
        'angazovana_osoba' => '\Ares\Client\Model\AngazovanaOsoba'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'evidence_od' => 'date',
        'angazovany_subjekt' => null,
        'v_evidenci' => null,
        'urad_evidence' => null,
        'angazovana_osoba' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'evidence_od' => 'evidenceOd',
        'angazovany_subjekt' => 'angazovanySubjekt',
        'v_evidenci' => 'vEvidenci',
        'urad_evidence' => 'uradEvidence',
        'angazovana_osoba' => 'angazovanaOsoba'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'evidence_od' => 'setEvidenceOd',
        'angazovany_subjekt' => 'setAngazovanySubjekt',
        'v_evidenci' => 'setVEvidenci',
        'urad_evidence' => 'setUradEvidence',
        'angazovana_osoba' => 'setAngazovanaOsoba'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'evidence_od' => 'getEvidenceOd',
        'angazovany_subjekt' => 'getAngazovanySubjekt',
        'v_evidenci' => 'getVEvidenci',
        'urad_evidence' => 'getUradEvidence',
        'angazovana_osoba' => 'getAngazovanaOsoba'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['evidence_od'] = isset($data['evidence_od']) ? $data['evidence_od'] : null;
        $this->container['angazovany_subjekt'] = isset($data['angazovany_subjekt']) ? $data['angazovany_subjekt'] : null;
        $this->container['v_evidenci'] = isset($data['v_evidenci']) ? $data['v_evidenci'] : null;
        $this->container['urad_evidence'] = isset($data['urad_evidence']) ? $data['urad_evidence'] : null;
        $this->container['angazovana_osoba'] = isset($data['angazovana_osoba']) ? $data['angazovana_osoba'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets evidence_od
     *
     * @return \DateTime
     */
    public function getEvidenceOd()
    {
        return $this->container['evidence_od'];
    }

    /**
     * Sets evidence_od
     *
     * @param \DateTime $evidence_od Datum poč&#225;tku evidence
     *
     * @return $this
     */
    public function setEvidenceOd($evidence_od)
    {
        $this->container['evidence_od'] = $evidence_od;

        return $this;
    }

    /**
     * Gets angazovany_subjekt
     *
     * @return \Ares\Client\Model\AngazovanySubjektSzr
     */
    public function getAngazovanySubjekt()
    {
        return $this->container['angazovany_subjekt'];
    }

    /**
     * Sets angazovany_subjekt
     *
     * @param \Ares\Client\Model\AngazovanySubjektSzr $angazovany_subjekt angazovany_subjekt
     *
     * @return $this
     */
    public function setAngazovanySubjekt($angazovany_subjekt)
    {
        $this->container['angazovany_subjekt'] = $angazovany_subjekt;

        return $this;
    }

    /**
     * Gets v_evidenci
     *
     * @return bool
     */
    public function getVEvidenci()
    {
        return $this->container['v_evidenci'];
    }

    /**
     * Sets v_evidenci
     *
     * @param bool $v_evidenci v evidenci
     *
     * @return $this
     */
    public function setVEvidenci($v_evidenci)
    {
        $this->container['v_evidenci'] = $v_evidenci;

        return $this;
    }

    /**
     * Gets urad_evidence
     *
     * @return string
     */
    public function getUradEvidence()
    {
        return $this->container['urad_evidence'];
    }

    /**
     * Sets urad_evidence
     *
     * @param string $urad_evidence urad_evidence
     *
     * @return $this
     */
    public function setUradEvidence($urad_evidence)
    {
        $this->container['urad_evidence'] = $urad_evidence;

        return $this;
    }

    /**
     * Gets angazovana_osoba
     *
     * @return \Ares\Client\Model\AngazovanaOsoba
     */
    public function getAngazovanaOsoba()
    {
        return $this->container['angazovana_osoba'];
    }

    /**
     * Sets angazovana_osoba
     *
     * @param \Ares\Client\Model\AngazovanaOsoba $angazovana_osoba angazovana_osoba
     *
     * @return $this
     */
    public function setAngazovanaOsoba($angazovana_osoba)
    {
        $this->container['angazovana_osoba'] = $angazovana_osoba;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
