<?php
/**
 * PodilVr
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ARES: REST API - veřejné
 *
 * REST rozhraní systému ARES
 *
 * OpenAPI spec version: 0.6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ares\Client\Model;
use \Ares\Client\ObjectSerializer;

/**
 * PodilVr Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PodilVr extends DatumZapisuVymazuUdajeVr 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PodilVr';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'text' => 'string',
        'vklad' => '\Ares\Client\Model\ObnosVr',
        'velikost_podilu' => '\Ares\Client\Model\ObnosVr',
        'splaceni' => '\Ares\Client\Model\ObnosVr',
        'zastavni_pravo' => '\Ares\Client\Model\ZastavniPravoVr[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'text' => null,
        'vklad' => null,
        'velikost_podilu' => null,
        'splaceni' => null,
        'zastavni_pravo' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'text' => 'text',
        'vklad' => 'vklad',
        'velikost_podilu' => 'velikostPodilu',
        'splaceni' => 'splaceni',
        'zastavni_pravo' => 'zastavniPravo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'text' => 'setText',
        'vklad' => 'setVklad',
        'velikost_podilu' => 'setVelikostPodilu',
        'splaceni' => 'setSplaceni',
        'zastavni_pravo' => 'setZastavniPravo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'text' => 'getText',
        'vklad' => 'getVklad',
        'velikost_podilu' => 'getVelikostPodilu',
        'splaceni' => 'getSplaceni',
        'zastavni_pravo' => 'getZastavniPravo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }




    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
        $this->container['vklad'] = isset($data['vklad']) ? $data['vklad'] : null;
        $this->container['velikost_podilu'] = isset($data['velikost_podilu']) ? $data['velikost_podilu'] : null;
        $this->container['splaceni'] = isset($data['splaceni']) ? $data['splaceni'] : null;
        $this->container['zastavni_pravo'] = isset($data['zastavni_pravo']) ? $data['zastavni_pravo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text text
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets vklad
     *
     * @return \Ares\Client\Model\ObnosVr
     */
    public function getVklad()
    {
        return $this->container['vklad'];
    }

    /**
     * Sets vklad
     *
     * @param \Ares\Client\Model\ObnosVr $vklad vklad
     *
     * @return $this
     */
    public function setVklad($vklad)
    {
        $this->container['vklad'] = $vklad;

        return $this;
    }

    /**
     * Gets velikost_podilu
     *
     * @return \Ares\Client\Model\ObnosVr
     */
    public function getVelikostPodilu()
    {
        return $this->container['velikost_podilu'];
    }

    /**
     * Sets velikost_podilu
     *
     * @param \Ares\Client\Model\ObnosVr $velikost_podilu velikost_podilu
     *
     * @return $this
     */
    public function setVelikostPodilu($velikost_podilu)
    {
        $this->container['velikost_podilu'] = $velikost_podilu;

        return $this;
    }

    /**
     * Gets splaceni
     *
     * @return \Ares\Client\Model\ObnosVr
     */
    public function getSplaceni()
    {
        return $this->container['splaceni'];
    }

    /**
     * Sets splaceni
     *
     * @param \Ares\Client\Model\ObnosVr $splaceni splaceni
     *
     * @return $this
     */
    public function setSplaceni($splaceni)
    {
        $this->container['splaceni'] = $splaceni;

        return $this;
    }

    /**
     * Gets zastavni_pravo
     *
     * @return \Ares\Client\Model\ZastavniPravoVr[]
     */
    public function getZastavniPravo()
    {
        return $this->container['zastavni_pravo'];
    }

    /**
     * Sets zastavni_pravo
     *
     * @param \Ares\Client\Model\ZastavniPravoVr[] $zastavni_pravo zastavni_pravo
     *
     * @return $this
     */
    public function setZastavniPravo($zastavni_pravo)
    {
        $this->container['zastavni_pravo'] = $zastavni_pravo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
